# Generated by Django 5.2.6 on 2025-10-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authot',
            new_name='author',
        ),
    ]
